{
 "title": "Etherum - OPS - Alerting",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Block (https://turbogeth.badger.guru)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocks{chain=~\"..*\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Total AUM - USD",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sett{param=\"usdBalance\"})",
     "legendFormat": "Grand Total"
    },
    {
     "expr": "sum(sett{token=~\".*crv.*\", param=\"usdBalance\"})",
     "legendFormat": "Curve Pools"
    },
    {
     "expr": "sum(sett{token=\"WBTC\", param=\"usdBalance\"}) ",
     "legendFormat": "Yearn Pool(s)"
    },
    {
     "expr": "sett{token=\"slpWbtcEth\", param=\"usdBalance\"} ",
     "legendFormat": "WBTC/ETH LP"
    },
    {
     "expr": "sum(sett{token=~\".*WbtcBadger.*\", param=\"usdBalance\"})",
     "legendFormat": "BADGER LP"
    },
    {
     "expr": "sum(sett{token=~\".*WbtcDigg.*\", param=\"usdBalance\"} )",
     "legendFormat": "DIGG LP"
    },
    {
     "expr": "sett{token=\"DIGG\", param=\"totalSupply\"} * on (token) sett{token=\"DIGG\", param=\"pricePerShare\"} * on(token) coingecko_prices{token=\"DIGG\", countercurrency=\"usd\"}",
     "legendFormat": "bDIGG"
    },
    {
     "expr": "sett{token=\"BADGER\", param=\"usdBalance\"} ",
     "legendFormat": "bBADGER"
    },
    {
     "expr": "sum(sett{sett=~\"b.*CVX\", param=\"usdBalance\"}) + sum(sett{sett=~\"b.*cvxCRV\",param=\"usdBalance\"})",
     "legendFormat": "Convex Helpers"
    }
   ]
  },
  {
   "title": "Badger rewards",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rewards{token=\"BADGER\",chain=~\"ETH\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "ARB Badger Rewards",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rewards{token=\"BADGER\",chain=~\"ARB\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Digg rewards",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rewards{token='DIGG'}", "legendFormat": "{{token}}" }
   ]
  },
  {
   "title": "Time since last cycle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-(badgertree{chain=~\"..*\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "PPFS increase over 48 hours",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sett{param=\"pricePerShare\", sett!~\"bslpWbtcEth\", chain=~\"..*\"}[48h])",
     "legendFormat": "{{chain}}:{{sett}}"
    }
   ]
  },
  {
   "title": "No ppfs increase in 72h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(sett{param=\"pricePerShare\", chain=~\"..*\", sett!~\"bslpWbtcEth\"}[72h]) == 0",
     "legendFormat": "{{chain}}:{{sett}}"
    }
   ]
  },
  {
   "title": "Badger Ops - ETH - Ethereum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "wallets{token=\"ETH\", param=\"balance\", walletName=~\"ops_.*\", walletName!~\"ops_multisig\", chain=\"ETH\"}",
     "legendFormat": "{{walletName}} "
    }
   ]
  },
  {
   "title": "Stuck Subgraphs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "delta(deployment_head[30m])==0", "legendFormat": "{{deployment}}-{{network}}" },
    {}
   ]
  },
  {
   "title": "Treasury (non-badger/digg)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wallets{param=\"usdBalance\", token!~\".*BADGER\", token!~\".*DIGG\", walletName!~\"uniswap_rewards\"}) != 0",
     "legendFormat": "Grand Total"
    },
    {
     "expr": "sum by(token) (wallets{param=\"usdBalance\", token!~\".*BADGER\", token!~\".*DIGG\",  walletName!~\"uniswap_rewards\"}) != 0",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Treasury (native assets)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "BADGER" }
   ],
   "targets": [
    {
     "expr": "sum by (chain) (wallets{param=\"balance\", token=~\".*BADGER\"})",
     "legendFormat": "{{chain}}:BADGER"
    },
    {
     "expr": "sum(wallets{param=\"balance\", token=~\".*DIGG\"})",
     "legendFormat": "DIGG"
    },
    {
     "expr": "sum(wallets{token=~\".*Digg\", param=\"balance\"})/2 != 0 ",
     "legendFormat": "DIGG LP (DIGG only))"
    }
   ]
  },
  {
   "title": "PPFS - Ethereum - PPFS decrease",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "delta(sett{param=\"pricePerShare\", sett!~\"bslpWbtcEth\", chain=\"ETH\"}[10m]) < 0",
     "legendFormat": "{{sett}}"
    }
   ]
  }
 ]
}