{
 "title": "ourGraph Metrics v2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocks", "legendFormat": "{{chain}}" }
   ]
  },
  {
   "title": "Block head by Graph (ETH)",
   "type": "stat",
   "gridPos": { "h": 23, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deployment_head{instance=\"bgraph-eth-metrics.badger.guru:443\"}",
     "legendFormat": "{{job}}-{{deployment}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "gauge",
   "description": "How many graphs are indexing on this node",
   "gridPos": { "h": 4, "w": 10, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deployment_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eth_rpc_errors[$__rate_interval])",
     "legendFormat": "{{job}}-{{deployment}}"
    },
    {}
   ]
  },
  {
   "title": "Block Process duration",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(deployment_block_processing_duration_count [$__rate_interval])",
     "legendFormat": "{{job}}-{{deployment}}"
    }
   ]
  },
  {
   "title": "Block head by Graph (MATIC)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deployment_head{instance=\"bgraph-matic-metrics.badger.guru:443\"}",
     "legendFormat": "{{job}}-{{deployment}}"
    }
   ]
  }
 ]
}